# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pF5tnm3v5ULgBdiwUSUg9CbyqfkG2sY-
"""

from google.colab import files
up=files.upload()

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score

df = pd.read_csv("Global_Climate_Change_Data_2020_2025.csv")

label_encoders = {}
categorical_cols = ['Continent', 'Country']

for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

X = df.drop("Climate_Risk_Index", axis=1)
y = df["Climate_Risk_Index"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Absolute Error:", mae)
print("R² Score:", r2)

importances = pd.Series(model.feature_importances_, index=X.columns)
print(importances.sort_values(ascending=False))

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv("Global_Climate_Change_Data_2020_2025.csv")

plt.figure(figsize=(10,5))
sns.barplot(data=df, x='Country', y='CO2_Emissions(Mt)')
plt.xticks(rotation=45)
plt.title("CO₂ Emissions by Country")
plt.show()

plt.figure(figsize=(10,5))
sns.lineplot(data=df, x='Year', y='Avg_Temperature(°C)', hue='Country')
plt.title("Temperature Trend Over Time")
plt.show()

plt.figure(figsize=(10,6))
sns.heatmap(df.select_dtypes(include='number').corr(), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

plt.figure(figsize=(7,5))
sns.scatterplot(data=df, x='CO2_Emissions(Mt)', y='Climate_Risk_Index', hue='Continent')
plt.title("CO₂ vs Climate Risk Index")
plt.show()

y_pred = model.predict(X_test)
print(y_pred)

new_data = [[2024, 2, 5, 28.4, 450.2, 3.1]]
# [Year, Continent, Country, Temp, CO2, SeaLevel]

prediction = model.predict(new_data)
print("Predicted Climate Risk Index:", prediction[0])

import pickle
import google.colab

Gobal_model= open('Gobal_model.pkl','wb')
pickle.dump(model,Gobal_model)

files.download('Gobal_model.pkl')

